### ISSUE TITLE
Unwrap for == and != comparisons

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#116]
We must unwrap optionals use in `==` and `!=` comparisons in order to preserve semantics.
```
-- Error Log from JUnit --
Class: edu.cuny.hunter.optionalrefactoring.ui.tests.ConvertNullToOptionalRefactoringTest
Method: testComparisonLocalVariable
Actual: package p;

import java.util.Optional;

class A {
	void m() {
		Object o1 = new Object();
		Object o2 = new Object();

		boolean b = o2 == o1;

		Optional<Object> o3 = Optional.empty();
		Optional<Object> o4 = Optional.of(new Object());

		b = o3 == o4;
	}
}
Expected: package p;

import java.util.Optional;

class A {
	void m() {
		Object o1 = new Object();
		Object o2 = new Object();
		
		boolean b = o2 == o1;

		Optional<Object> o3 = Optional.empty();
		Optional<Object> o4 = Optional.ofNullable(new Object());

		b = o3.orElse(null) == o4.orElse(null);
	}
}
Stack Trace:
junit.framework.ComparisonFailure: expected:<... o2 = new Object();
[		
		boolean b = o2 == o1;

		Optional<Object> o3 = Optional.empty();
		Optional<Object> o4 = Optional.ofNullable(new Object());

		b = o3.orElse(null) == o4.orElse(null)];
	}
}> but was:<... o2 = new Object();
[
		boolean b = o2 == o1;

		Optional<Object> o3 = Optional.empty();
		Optional<Object> o4 = Optional.of(new Object());

		b = o3 == o4];
	}
}>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.TestCase.assertEquals(TestCase.java:261)
	at org.eclipse.jdt.ui.tests.refactoring.RefactoringTest.assertEqualLines(RefactoringTest.java:629)
	at org.eclipse.jdt.ui.tests.refactoring.RefactoringTest.assertEqualLines(RefactoringTest.java:613)
	at edu.cuny.hunter.optionalrefactoring.ui.tests.ConvertNullToOptionalRefactoringTest.transformationHelper(ConvertNullToOptionalRefactoringTest.java:488)
	at edu.cuny.hunter.optionalrefactoring.ui.tests.ConvertNullToOptionalRefactoringTest.testComparisonLocalVariable(ConvertNullToOptionalRefactoringTest.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23)
	at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.extensions.TestSetup.run(TestSetup.java:27)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:124)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:232)
	at org.eclipse.pde.internal.junit.runtime.PlatformUITestHarness.lambda$0(PlatformUITestHarness.java:45)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5026)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4586)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.runApp(NonUIThreadTestApplication.java:55)
	at org.eclipse.pde.internal.junit.runtime.UITestApplication.runApp(UITestApplication.java:46)
	at org.eclipse.pde.internal.junit.runtime.NonUIThreadTestApplication.start(NonUIThreadTestApplication.java:49)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
``

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/868728567449515)

**Comment by khatchad** [comment]
@orenwf I actually used "unwrap" here :).
