### ISSUE TITLE
Exception during evaluation of VietPad

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Null-to-Optional-Eclipse-Plugin#128]
@orenwf, we're getting an exception when running the evaluator on VietPad:
```
!ENTRY edu.cuny.hunter.optionalrefactoring.eval 4 0 2018-10-25 17:19:10.935
!MESSAGE Encountered exception during evaluation
!STACK 1
VietPad121	=VietPad121/\/usr\/lib\/jvm\/java-8-openjdk-amd64\/jre\/lib\/rt.jar<java.io(BufferedReader.class[BufferedReader~readLine	-1	-1	-1	edu.cuny.hunter.optionalrefactoring.core.exceptions.HarvesterJavaModelException	java.lang.String readLine() {key=Ljava/io/BufferedReader;.readLine()Ljava/lang/String;|Ljava/io/IOException;} [in BufferedReader [in BufferedReader.class [in java.io [in /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar]]]]	org.eclipse.jdt.internal.core.ResolvedBinaryMethod	java.lang.String readLine() {key=Ljava/io/BufferedReader;.readLine()Ljava/lang/String;|Ljava/io/IOException;} [in BufferedReader [in BufferedReader.class [in java.io [in /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar]]]]			
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.NullPropagator.descend(NullPropagator.java:286)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.ASTNodeProcessor.processDescent(ASTNodeProcessor.java:1714)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.N2ONodeProcessor.descend(N2ONodeProcessor.java:202)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.N2ONodeProcessor.ascend(N2ONodeProcessor.java:102)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.ASTNodeProcessor.processAscent(ASTNodeProcessor.java:778)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.NullPropagator.ascend(NullPropagator.java:172)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.ASTNodeProcessor.processAscent(ASTNodeProcessor.java:1007)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.N2ONodeProcessor.ascend(N2ONodeProcessor.java:157)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.ASTNodeProcessor.processAscent(ASTNodeProcessor.java:1098)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.NullPropagator.process(NullPropagator.java:543)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.RefactorableHarvester$1.acceptSearchMatch(RefactorableHarvester.java:152)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.report(MatchLocator.java:2170)
	at org.eclipse.jdt.internal.core.search.matching.LocalVariableLocator.matchReportReference(LocalVariableLocator.java:71)
	at org.eclipse.jdt.internal.core.search.matching.PatternLocator.matchReportReference(PatternLocator.java:448)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2626)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:3268)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.reportMatching(MatchLocator.java:2847)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2022)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1336)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1377)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1519)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:112)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:250)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:595)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.RefactorableHarvester.harvestRefactorableContexts(RefactorableHarvester.java:165)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.ConvertNullToOptionalRefactoringProcessor.process(ConvertNullToOptionalRefactoringProcessor.java:330)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.ConvertNullToOptionalRefactoringProcessor.process(ConvertNullToOptionalRefactoringProcessor.java:408)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.ConvertNullToOptionalRefactoringProcessor.process(ConvertNullToOptionalRefactoringProcessor.java:424)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.ConvertNullToOptionalRefactoringProcessor.process(ConvertNullToOptionalRefactoringProcessor.java:378)
	at edu.cuny.hunter.optionalrefactoring.core.refactorings.ConvertNullToOptionalRefactoringProcessor.checkFinalConditions(ConvertNullToOptionalRefactoringProcessor.java:132)
	at org.eclipse.ltk.core.refactoring.participants.ProcessorBasedRefactoring.checkFinalConditions(ProcessorBasedRefactoring.java:225)
	at org.eclipse.ltk.core.refactoring.Refactoring.checkAllConditions(Refactoring.java:165)
	at edu.cuny.hunter.optionalrefactoring.eval.handlers.EvaluateConvertNullToOptionalRefactoringHandler.lambda$0(EvaluateConvertNullToOptionalRefactoringHandler.java:92)
	at org.eclipse.core.runtime.jobs.Job$1.run(Job.java:164)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
Please fix this ASAP as @walleXD is getting blocked on working on the evaluator.

BTW, why are we processing code in `rt.jar`? That's the java library stuff. We want to only process elements inside the input project.

## Regression
This does not happen in b6f7eb2a138e6ad59d0d638d8e524a7359d1c45c but does happen in 9eed127b1fd90a8cac72e77c6cae7b7228e19a0d.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/274838528047159/883452291080076)

**Comment by orenwf** [comment]
@walleXD  What are you running N2O on, the whole project ? or a specific package or class ? Would help me recreate the exception.

**Comment by khatchad** [comment]
It was the entire project.
